version: "3"

networks:
  origin:
  private:
  public:

volumes:
  data:

services:
  db:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_DB: sales_db
      POSTGRES_USER: lehungvi
      POSTGRES_PASSWORD: lehungvi
    ports:
      - 5432
    networks:
      - private
    volumes:
      - data:/var/lib/postgresql/data

  sales-web-app:
    build: ./sales_web_app
    ports:
      - 8000:8000
    depends_on:
      - db
    environment: &env
      SQLALCHEMY_DATABASE_URI: postgresql://lehungvi:lehungvi@db:5432/sales_db
